### ISSUE TITLE
Calculator::GetI() не всегда возвращает значение

### ISSUE THREAD

**Issue by ghost** [DmitryPl/Multithreaded-Calculator#3]
Функция **Calculator::GetI** имеет несколько веток if/else if, однако нет ветки конечного else, поэтому функция не всегда вернет значение:
`Calculator.cpp:332:1: warning: control may reach end of non-void function [-Wreturn-type]`

Даже если тако ситуации на самом деле быть не может, следует добавить в конец функции возврат какого-л. значения, либо сделать конечный else, где будет выкинуто исключение и возвращено значение.

В других функциях подобных ситуаций не наблюдается, обратите внимание на их работу.

**Comment by DmitryPl** [comment]
Исправил

**Comment by ghost** [comment]
все равно ругается, но теперь понятно, что в случае исключения возвращать значение необязательно
