### ISSUE TITLE
По умолчанию отключить debug-флаги 

### ISSUE THREAD

**Issue by ghost** [DmitryPl/Multithreaded-Calculator#4]
В **System.hpp:21** правильным будет по умолчанию выставить все отладочные флаги в false.

Если требуется отладить работу программы с соотв. выводом, то следует включать данные флаги либо при подаче ключа '-g' (сложнее), либо командами (как сделано у Вас сейчас), либо подавать при компиляции определение вида `-DDEBUG`, а в коде включать флаги:
```
#if defined(DEBUG)
    bool DEBUG_SUM = true;
    bool DEBUG_SYS = true;
    bool DEBUG_FACT = true;
#else
    bool DEBUG_SUM = false;
    bool DEBUG_SYS = false;
    bool DEBUG_FACT = false;
#endif
```

Соотв-но, отразить данные особенности в README.

**Comment by DmitryPl** [comment]
Сделал последний предложенный вариант
Осталось переписать README
