### ISSUE TITLE
Улучшение вывода ошибок ввода формулы

### ISSUE THREAD

**Issue by ghost** [DmitryPl/Multithreaded-Calculator#5]
Т.к. обработчик ошибок ввода у Вас довольно простой, можно существенно упростить чтение его вывода.

Рассмотрим пример:
```
sin(pi/2)*e+cos((sin(0))
string:sin(pi/2)*e+cos((sin(0))
char:
place:24
Error - GetFunc - )
try again
```

Искать вручную 24й символ в формуле не очень удобно, поэтому можно сделать так:
```
sin(pi/2)*e+cos((sin(0))
string:
sin(pi/2)*e+cos((sin(0))
                       ^
Error - GetFunc - )
try again
```

Т.е. вместо вывода номера символа с ошибкой, выводить пробелы в количестве (номер символа - 1), затем символ `^` для показа позиции в формуле выше. Формулу выводить, соотв-но, в новой строке (лучше вывести повторно).

Сделать несложно, а пользы будет в разы больше.

**Comment by DmitryPl** [comment]
Сделал

**Comment by ghost** [comment]
спасибо, так гораздо лучше
корректность позиции не проверял, верю на слово
