### ISSUE TITLE
Использование типов uint, ulong

### ISSUE THREAD

**Issue by ghost** [DmitryPl/Multithreaded-Calculator#6]
Для VS Code эти типы определены на уровне среды.
В компиляторе этих типов не существует, т.е. при сборке без среды будут ошибки.

Было бы грамотным либо использовать вместо них `unsigned int` / `unsigned long`, либо определить их явно:
```
typedef unsigned int uint;
typedef unsigned long ulong;
```

**Comment by DmitryPl** [comment]
done
